apiVersion: v1
kind: Service
metadata:
  name: web-app-clusterip-svc
spec:
  selector:
    tier: frontend
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 4001
    protocol: TCP