apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-blue
spec:
  selector:
    matchLabels:
      app: nginx
      role: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        role: blue
    spec:
      securityContext: #https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
        runAsUser: 101
        runAsGroup: 101
        #fsGroup: 101
      containers:
      - name:  nginx-blue
        image: 991654915716.dkr.ecr.eu-central-1.amazonaws.com/demo:nginx-blue-v1.0
        ports:
        - containerPort:  9000
        #securityContext:
          #allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: blue-test-svc
  labels:
    app: nginx
    role: blue
    env: temp
spec:
  selector:
    app: nginx
    role: blue
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP