apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-green
spec:
  selector:
    matchLabels:
      app: nginx
      role: green
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        role: green
    spec:
      containers:
      - name:  nginx-green
        image:  MYAPP:latest
        ports:
        - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: green-test-svc
  labels:
    app: nginx-green
    role: green
    env: temp
spec:
  selector:
    app: nginx-green
    role: green
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 80
    protocol: TCP