apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#  name: nginx-svc
# spec:
#  type: NodePort
#  selector:
#     app: nginx
#  ports:
#   - port: 8080
#     targetPort: 80
#     nodePort: 32000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#  name: nginx-svc
# spec:
#  type: LoadBalancer
#  selector:
#     app: nginx
#  ports:
#   - port: 8080
#     targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-svc
spec:
 type: ClusterIP
 selector:
    app: nginx
 ports:
  - port: 8080
    targetPort: 80