version: '3.7'

services:

  blue:
    container_name: nginx-blue
    image: 991654915716.dkr.ecr.eu-central-1.amazonaws.com/demo:nginx-blue-v1.0
    build:
      context: ./blue
      dockerfile: blue.dockerfile
    ports:
     - 8080:80
    

  green:
    container_name: nginx-green
    image: 991654915716.dkr.ecr.eu-central-1.amazonaws.com/demo:nginx-green-v1.0
    build:
      context: ./green
      dockerfile: green.dockerfile
    ports:
     - 8081:80